package M2_Practical15

object PolynomialFeatures {

  def main(args: Array[String]): Unit = {

    // Input data given in the practical example
    val data = List(1, 2, 3)

    // Polynomial degree
    val degree = 3

    // Generate polynomial features
    val polynomialFeatures = data.flatMap { value =>
      (1 to degree).map { power =>
        math.pow(value, power).toInt
      }
    }

    println("==============================================")
    println("        POLYNOMIAL FEATURE GENERATION")
    println("==============================================")

    println()
    println(s"Input Data : ${data.mkString("[", ", ", "]")}")
    println(s"Degree     : $degree")

    println()
    println("Polynomial Features:")
    println(polynomialFeatures.mkString("[", ", ", "]"))

    println()
    println("Feature Calculation:")

    data.foreach { value =>
      val features = (1 to degree).map { power =>
        math.pow(value, power).toInt
      }

      println(
        s"$value -> ${features.mkString("[", ", ", "]")}"
      )
    }

    println()
    println("Inference:")
    println("Polynomial features are generated by raising")
    println("each input value to powers from 1 up to degree 3.")

    println()
    println("==============================================")
    println("Program completed successfully.")
    println("==============================================")
  }
}